#!/bin/bash

sudo apt-get update
sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt-get update
sudo apt-get install -y docker-ce
sudo usermod -aG docker ubuntu
sudo curl -L https://github.com/docker/compose/releases/download/1.21.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
sudo systemctl enable docker
sudo systemctl start docker

wget https://raw.githubusercontent.com/SeredaYehor/Terraform_aws/main/nginx.conf
touch docker-compose.yml
cat << EOF > docker-compose.yml
version: '2'

volumes:
  nextcloud:

services:
  app:
    image: nextcloud:fpm
    restart: always
    volumes:
      - nextcloud:/var/www/html

  web:
    image: nginx
    restart: always
    ports:
      - 80:80
    links:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - app
EOF

docker-compose up -d
echo "Done"
