#!/bin/bash
mkdir /init_server
cd /init_server
sudo apt update
sudo apt install -y openvpn expect awscli
curl -fsSL https://get.docker.com -o get-docker.sh
sh get-docker.sh

declare -a files=("setupVPN.sh" "addVPNUser.sh" "ExpectSetupVPN" "ExpectAddUserVPN" "openvpn.conf")

for file in "${files[@]}"
do
   aws s3 cp  s3://terr-nextcloud-bucket/$file .
done


publicIP=`dig +short myip.opendns.com @resolver1.opendns.com`

sed -i "s/{{ host }}/${publicIP}/g" openvpn.conf
sudo chmod +x setupVPN.sh addVPNUser.sh ExpectSetupVPN ExpectAddUserVPN

./ExpectSetupVPN 1234567890

for key in "client" "nextcloud"
do
   ./ExpectAddUserVPN $key 1234567890
   sed -i '/redirect-gateway def1/d' $key.ovpn
   aws s3 cp $key.ovpn s3://terr-nextcloud-bucket/
done



