#!/bin/bash

sudo apt-get update
sudo apt-get install -y openvpn awscli
curl -fsSL https://get.docker.com -o get-docker.sh
sh get-docker.sh

aws s3 cp s3://terr-nextcloud-bucket/nextcloud.ovpn .
aws s3 cp s3://terr-nextcloud-bucket/docker-compose.yml .
aws s3 cp s3://terr-nextcloud-bucket/nginx.conf .

cp nextcloud.ovpn /etc/openvpn/client/nextcloud.conf
sudo systemctl start openvpn-client@nextcloud

vpn_ip=`ip -f inet addr show tun0  | awk '/inet / {print $2}' | cut -d/ -f1`
sed -i "s/{{ ip }}/${vpn_ip}/g" docker-compose.yml

sudo docker compose up -d



