version: '2'
volumes:
  nextcloud:
services:
  app:
    image: nextcloud:fpm
    restart: always
    volumes:
      - nextcloud:/var/www/html
  web:
    image: nginx
    restart: always
    ports:
      - {{ ip }}:80:80
    links:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    volumes_from:
      - app
